name: Generate Snake

on:
  schedule:
    # Runs every day at 18:30 UTC (which is 12:00 AM IST)
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: uppiii
          outputs: |
            dist/snake.svg

      - name: Push Snake to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
